from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one match, got {count}: {old[:120]!r}")
    with p.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text.replace(old, new))


# README: the API draft exists but remains unapproved.
replace_once("README.md", "`docs/API_CONTRACT.md`, `docs/view-contract.md` và `docs/traceability.md` chưa có trong repository. Các proposal P1 hiện có chưa được xem là approval cuối cùng hay cho phép viết implementation.", "`docs/API_CONTRACT.md` đã có bản Draft P1 để review; `docs/view-contract.md` và `docs/traceability.md` chưa có. Draft và các proposal P1 chưa phải approval cuối cùng hay cho phép viết implementation.")

# PLAN: align API deliverable status; keep Quiz and loyalty outside MVP gate.
replace_once("docs/PLAN.md", "| [docs/API_CONTRACT.md](API_CONTRACT.md) | Hợp đồng route/request/response/error/CSRF | Chưa tạo; chờ schema/permission proposals được duyệt |", "| [docs/API_CONTRACT.md](API_CONTRACT.md) | Hợp đồng route/request/response/error/CSRF | Draft P1 đã tạo; chờ review và approval |")
replace_once("docs/PLAN.md", "5. P1 duyệt BR-10, finance/freshness rules, search/guest lookup limitations và coupon redemption model.", "5. P1 duyệt finance/freshness rules, search/guest lookup limitations và coupon redemption model; BR-10 chỉ là gate nếu Quiz được đưa vào scope release.")
replace_once("docs/PLAN.md", "- [ ] Tạo `API_CONTRACT.md` sau approval schema/permissions: routes, methods, auth, CSRF, requests/responses/errors.", "- [x] Tạo `API_CONTRACT.md` Draft P1 để review; routes, methods, auth, CSRF, request/response/error details vẫn cần reconcile và approval sau schema/permissions review.")
replace_once("docs/PLAN.md", "- [ ] Pricing: hàng → subscription discount → coupon → points → shipping.\n- [ ] VND integer; percentage discount floor; fixed coupon không vượt eligible merchandise; một coupon/order.\n- [ ] Points cap 20% của eligible merchandise sau subscription/coupon, trước shipping.", "- [ ] Pricing MVP: giá hàng → coupon → shipping; subscription/points chỉ áp dụng nếu module tương lai được bật.\n- [ ] VND integer; percentage discount floor; fixed coupon không vượt eligible merchandise; một coupon/order.\n- [ ] Không triển khai points earning/redemption trong MVP; giữ BR-06 là quy tắc có điều kiện cho module tương lai.")
replace_once("docs/PLAN.md", "**Hoàn thành khi:** unit/integration tests cho từng bước giá, boundary quantity, coupon/points và mọi nhánh merge đều có kết quả deterministic.", "**Hoàn thành khi:** unit/integration tests cho các bước pricing thuộc MVP, boundary quantity, coupon và mọi nhánh merge sau khi P1 contract được duyệt đều có kết quả deterministic.")

# PROGRESS: record the existing draft accurately without marking the contract done.
replace_once("docs/PROGRESS.md", "| P1 | Schema, quyền, API/view contracts | In progress | TL/PD + BE/DB + FE + QA/INT | N/A | P0 Done | Chưa chạy acceptance tests | 2026-10-07 | TECH_STACK/schema/permissions proposals tồn tại, chờ review; API/view và P1 sign-off còn mở. |", "| P1 | Schema, quyền, API/view contracts | In progress | TL/PD + BE/DB + FE + QA/INT | N/A | P0 Done | Chưa chạy acceptance tests | 2026-10-07 | TECH_STACK/schema/permissions proposals và API Draft tồn tại, chờ review; view contract và P1 sign-off còn mở. |")
replace_once("docs/PROGRESS.md", "| P1-05 | P1 | Chốt API contract | Blocked | TL/PD + BE/FE + QA/INT | N/A | Chưa chạy | 2026-10-07 | Chờ schema/permission proposals được review; chưa tạo API contract. |", "| P1-05 | P1 | Chốt API contract | Blocked | TL/PD + BE/FE + QA/INT | N/A | Chưa chạy | 2026-10-07 | `docs/API_CONTRACT.md` Draft P1 đã tạo; chờ schema/permission review, reconcile và final approval. |")
replace_once("docs/PROGRESS.md", "| 2026-10-07 | Tạo P1 TECH_STACK/schema/permissions proposals; đồng bộ PLAN với P0 Done. Tests chưa chạy, proposals chờ approval. | TL/PD | `docs/TECH_STACK.md`, `docs/database-schema-proposal.md`, `docs/permissions-matrix.md`; không có implementation artifacts |", "| 2026-10-07 | Tạo P1 TECH_STACK/schema/permissions proposals; đồng bộ PLAN với P0 Done. Tests chưa chạy, proposals chờ approval. | TL/PD | `docs/TECH_STACK.md`, `docs/database-schema-proposal.md`, `docs/permissions-matrix.md`; không có implementation artifacts |\n| 2026-10-07 | Tạo API contract Draft P1 để review; acceptance tests và final P1 approval chưa chạy/chưa đạt. | TL/PD | `docs/API_CONTRACT.md`; không có implementation artifacts |")

# PRD: align coupon policy, bank-transfer permission, roadmap Quiz and Guest fields.
replace_once("docs/PRD.md", "**Phạm vi coupon cần lưu trong thiết kế:** coupon áp dụng cho sản phẩm/danh mục nào, có điều kiện loại trừ subscription hay không và giá trị hàng đủ điều kiện được tính ra sao. Nếu chưa có quyết định riêng, triển khai theo nguyên tắc coupon áp dụng toàn đơn và cộng dồn với subscription. **[Đề xuất triển khai mặc định]**", "**Theo DEC-024:** coupon dùng category allowlist; allowlist rỗng không giới hạn category; quota chỉ release khi hủy trước `paid`, còn order đã `paid` giữ quota kể cả refund. Còn chờ review: cách xử lý sản phẩm thuộc nhiều category, phân bổ discount vào snapshot và canonical Guest identity. Không dùng fallback mặc định để thay quyết định còn mở; subscription/points chưa bật trong MVP.")
replace_once("docs/PRD.md", "- **BR-08:** `unpaid → paid/failed`; `refunded` khi hoàn tiền đơn đã trả; COD chuyển `paid` khi hoàn tất; chuyển khoản do nhân viên xác nhận thủ công. **[Gốc]**", "- **BR-08:** `unpaid → paid/failed`; `refunded` khi hoàn tiền đơn đã trả; COD chuyển `paid` khi hoàn tất; xác nhận chuyển khoản Admin-only theo DEC-028. **[Gốc + quyết định quyền đã duyệt]**")
replace_once("docs/PRD.md", "### 6.4. Quiz — BR-10 đã chốt cho roadmap", "### 6.4. Quiz — BR-10 gốc, chỉ áp dụng nếu được duyệt đưa vào release")
replace_once("docs/PRD.md", "Nguồn nền: [Gốc] BR-10, FR-QZ-02, §10.4. Công thức đầy đủ và quy tắc hòa: [Đã duyệt].", "Nguồn nền: [Gốc] BR-10, FR-QZ-02, §10.4. Công thức là nội dung roadmap, không phải quyết định triển khai MVP; cần approval riêng trước khi thực hiện.")
replace_once("docs/PRD.md", "1. Guest mở `/tra-cuu-don`.\n2. Nhập mã đơn và số điện thoại.\n3. Hệ thống kiểm tra cặp thông tin và chỉ trả về đơn phù hợp.\n4. Hiển thị trạng thái, timeline và thông tin cần thiết; không làm lộ dữ liệu đơn của người khác.", "1. Guest mở `/tra-cuu-don`.\n2. Nhập mã đơn và số điện thoại.\n3. Hệ thống kiểm tra cặp thông tin và chỉ trả về đơn phù hợp.\n4. Hiển thị dữ liệu allowlist đã được duyệt cho Guest lookup; không trả PII hoặc làm lộ dữ liệu đơn của người khác. Chi tiết response field-by-field phải theo P1 contract được sign-off.")

# SPEC: narrow batch exception and align transfer-confirmation owner.
replace_once("docs/SPEC.md", "| FR-BT-01 | MVP tối thiểu | Product detail chọn được batch mới nhất còn hàng và hiển thị ngày rang/mốc thưởng thức theo BR-11. |", "| FR-BT-01 | Roadmap (trừ dữ liệu tối thiểu đã duyệt cho FR-CT-06) | Product detail dùng dữ liệu batch tối thiểu để chọn batch mới nhất còn hàng và hiển thị ngày rang/mốc thưởng thức theo BR-11; không bao gồm batch-management workflow. |")
replace_once("docs/SPEC.md", "`unpaid → paid | failed`; `refunded` khi hoàn tiền order đã trả. COD thành `paid` khi order `completed`; chuyển khoản do Staff/Admin có quyền xác nhận thủ công theo P1 permissions/API contract. **[Gốc]**", "`unpaid → paid | failed`; `refunded` khi hoàn tiền order đã trả. COD thành `paid` khi order `completed`; xác nhận chuyển khoản Admin-only theo DEC-028. **[Gốc + quyết định quyền đã duyệt]**")

# API: preserve approved baseline; label unresolved mechanics and scope full batch management out.
replace_once("docs/API_CONTRACT.md", "- Trim input và chuẩn hóa Unicode NFC.\n- Tìm tiếng Việt không phân biệt dấu.\n- Query sau chuẩn hóa dưới 2 ký tự trả `200` với `data: []`.\n- Tối đa 8 suggestion.\n- Debounce 250 ms thuộc UI; server vẫn enforce giới hạn.\n- p95 target ≤300 ms, đo tại server endpoint.\n\n**Benchmark profile đã chốt cho draft:** 10.000 active products, 50 concurrent users, warm-up 1 phút, đo 5 phút, tối thiểu 10.000 requests. Benchmark gate chạy trong CI; báo cáo phải ghi fixture/dataset, request mix, resource limits, runtime versions, topology và môi trường. Chưa có kết quả benchmark; target chưa được xác minh.\n\n**Đề xuất — chờ duyệt:** fixture gồm 70% product search, 20% suggestions và 10% filter/list requests; query mix có dấu/không dấu, từ ngắn, không match và nhiều match; seed cố định, ghi hash/phiên bản fixture. Cần thêm test case benchmark riêng vào TEST_PLAN; hiện chưa có trong đó.", "- **Đã duyệt:** tối thiểu 2 ký tự, tối đa 8 suggestions, debounce UI 250 ms, p95 target ≤300 ms.\n- **Đề xuất — chờ duyệt:** Trim và chuẩn hóa Unicode NFC; tìm không phân biệt dấu; query sau chuẩn hóa dưới 2 ký tự trả `200` với `data: []`; p95 đo tại server endpoint. Cách chuẩn hóa tiếng Việt, semantics ngưỡng và scope đo p95 chưa được chốt.\n- **Đề xuất benchmark — chờ duyệt, chưa chạy:** profile 10.000 active products, 50 concurrent users, warm-up 1 phút, đo 5 phút, tối thiểu 10.000 requests. Fixture gợi ý gồm 70% product search, 20% suggestions và 10% filter/list requests; query mix có dấu/không dấu, từ ngắn, không match và nhiều match; seed cố định, ghi hash/phiên bản fixture. Benchmark CI gate, fixture và tiêu chí báo cáo phải được duyệt và thêm vào TEST_PLAN trước khi dùng làm acceptance.")
replace_once("docs/API_CONTRACT.md", "- Guest phone chuẩn hóa E.164 trước HMAC. Redemption lưu digest và key version; ghi mới bằng key hiện tại; dual-read trong rotation tới khi coupon window/redemptions dùng key cũ hết hạn hoặc được xử lý.", "- **Đề xuất — chờ duyệt theo OPEN-005:** chuẩn hóa Guest phone E.164 trước HMAC; lưu digest/key version; ghi mới bằng key hiện tại và dual-read khi rotation. Canonical normalization và điều kiện kết thúc dual-read chưa được chốt.")
replace_once("docs/API_CONTRACT.md", "- Format validate trước lookup; malformed request không tính lượt.\n- Rolling window 15 phút: năm request hợp lệ được phép; request hợp lệ thứ sáu bắt đầu cooldown 15 phút.\n- Mismatch vẫn là request hợp lệ và được tính. Mismatch trả `404` neutral, không tiết lộ order tồn tại.\n- Cooldown trả `429` cùng `Retry-After`.\n- Trusted forwarded IP chỉ lấy từ proxy được cấu hình rõ; IP dùng HMAC/hash, không log IP rõ.\n- Rate-limit store lỗi thì fail closed; không thực hiện lookup.\n- Response chỉ gồm order ID, ngày, trạng thái, items và totals; không trả người nhận, số điện thoại, địa chỉ, payment status/history hoặc dữ liệu fulfillment nhạy cảm.", "- **Đã duyệt:** Guest lookup không trả PII; mismatch trả lỗi trung tính; rate-limit baseline là 5 lần/15 phút theo IP hash và cooldown 15 phút.\n- **Đề xuất — chờ duyệt theo OPEN-008:** malformed request không tính lượt; rolling-window semantics, request thứ sáu bắt đầu cooldown, mismatch tính lượt, `Retry-After`, trusted proxy allowlist, HMAC/hash chi tiết và fail-closed khi rate-limit store lỗi.\n- **Đề xuất field-level — chờ duyệt:** response chỉ gồm order ID, ngày, trạng thái, items và totals; không trả người nhận, số điện thoại, địa chỉ, payment status/history hoặc dữ liệu fulfillment nhạy cảm. Cần sign-off field-by-field theo DEC-030/permissions matrix trước khi xem là API guarantee.")
replace_once("docs/API_CONTRACT.md", "| `POST /api/v1/admin/orders/{orderId}/refunds` | Admin-only | Tạo refund case duy nhất cho order và attempt đầu ở trạng thái `pending`; amount full lấy từ paid total, không nhận amount tùy client. `Idempotency-Key` bắt buộc. |", "| `POST /api/v1/admin/orders/{orderId}/refunds` | **Đề xuất — chờ permission/API approval:** Admin-only | Tạo refund case duy nhất cho order và attempt đầu ở trạng thái `pending`; amount full lấy từ paid total, không nhận amount tùy client. `Idempotency-Key` bắt buộc. |")
replace_once("docs/API_CONTRACT.md", "| `POST /api/v1/admin/refunds/{refundId}/attempts` | Admin-only | Tạo attempt retry mới chỉ khi attempt trước `failed`; attempt row/event log append-only. `Idempotency-Key` bắt buộc. |", "| `POST /api/v1/admin/refunds/{refundId}/attempts` | **Đề xuất — chờ permission/API approval:** Admin-only | Tạo attempt retry mới chỉ khi attempt trước `failed`; attempt row/event log append-only. `Idempotency-Key` bắt buộc. |")
replace_once("docs/API_CONTRACT.md", "| `POST /api/v1/admin/refunds/{refundId}/attempts/{attemptId}/result` | Admin-only | Append result event `succeeded` hoặc `failed` cho attempt đang `pending`; `Idempotency-Key` bắt buộc. Success yêu cầu external reference; failure lưu reason. |", "| `POST /api/v1/admin/refunds/{refundId}/attempts/{attemptId}/result` | **Đề xuất — chờ permission/API approval:** Admin-only | Append result event `succeeded` hoặc `failed` cho attempt đang `pending`; `Idempotency-Key` bắt buộc. Success yêu cầu external reference; failure lưu reason. |")
replace_once("docs/API_CONTRACT.md", "- Response chỉ gồm order ID, ngày, trạng thái, items và totals; không trả người nhận, số điện thoại, địa chỉ, payment status/history hoặc dữ liệu fulfillment nhạy cảm.", "- Response field list tại dòng này là **Đề xuất — chờ field-level permission sign-off**; Guest lookup không trả PII là nguyên tắc đã duyệt.")
replace_once("docs/API_CONTRACT.md", "| `GET /api/v1/admin/products/{productId}/batches` | Admin | Filter `status`, `roast_date_from`, `roast_date_to`; sort `roast_date_asc`, `roast_date_desc`, `batch_code_asc`. |\n| `POST /api/v1/admin/products/{productId}/batches` | Admin | Tạo `batch_code`, `roast_date`, `produced_qty_g`, `status`. |\n| `PATCH /api/v1/admin/batches/{batchId}` | Admin | Sửa metadata/date chỉ khi chưa có allocation. |", "| `GET /api/v1/admin/products/{productId}/batches` | **Ngoài MVP — roadmap** | Batch listing/filter. |\n| `POST /api/v1/admin/products/{productId}/batches` | **Ngoài MVP — roadmap** | Tạo batch. |\n| `PATCH /api/v1/admin/batches/{batchId}` | **Ngoài MVP — roadmap** | Sửa metadata/date. |")
replace_once("docs/API_CONTRACT.md", "- Batch code là identifier ổn định, unique, không ép format.\n- Không đổi product sau khi tạo batch.\n- Không suy tồn từ `produced_qty_g`.\n- **Đề xuất — chờ duyệt:** status defaults `draft`, `active`, `archived`; enum và transition vẫn chờ schema approval.\n- **Đề xuất — chờ duyệt:** batch đã có allocation không sửa metadata; chỉ archive nếu schema/permission xác nhận thao tác này an toàn.\n- Không có workflow Staff gán batch hoặc tạo lot trong MVP.", "- **MVP:** chỉ dữ liệu batch tối thiểu cần cho product detail/freshness theo FR-CT-06; không có batch-management workflow hoặc endpoint Admin tạo/sửa batch.\n- Không suy tồn từ `produced_qty_g`; dữ liệu batch phải lấy từ inventory model được duyệt.\n- Các endpoint quản trị batch, status enum/transitions và edit/archive policy thuộc roadmap hoặc cần scope approval riêng.")

# Permissions: refund authorization is unresolved; batch management is not an MVP permission.
replace_once("docs/permissions-matrix.md", "Đã duyệt: Staff chuyển order qua trạng thái hợp lệ, điều chỉnh tồn có audit; Admin-only cho giá, coupon, config, role và xác nhận thanh toán; không xóa dữ liệu/lịch sử.", "Đã duyệt: Staff chuyển order qua trạng thái hợp lệ, điều chỉnh tồn có audit; Admin-only cho giá, coupon, config, role và xác nhận thanh toán; không xóa dữ liệu/lịch sử. Quyền refund chưa có quyết định riêng, mặc định deny cho tới khi permission/API được sign-off.")
replace_once("docs/permissions-matrix.md", "| Quản lý roast batch metadata | — | — | —* | Admin | Đề xuất Admin-only; điều chỉnh inventory riêng Staff/Admin. |", "| Quản lý roast batch metadata | — | — | —* | —* | Ngoài MVP theo scope batch tối thiểu; nếu scope roadmap được duyệt riêng thì cần ma trận quyền riêng. |")
replace_once("docs/permissions-matrix.md", "- Cancel paid mở/duy trì đúng một refund case cho order; attempts append-only. Retry sau failed tạo attempt mới, không ghi đè. Refund success mới restock atomically đúng một lần; Admin-only.", "- Cancel paid mở/duy trì đúng một refund case cho order; attempts append-only. Retry sau failed tạo attempt mới, không ghi đè. Refund success mới restock atomically đúng một lần. **Đề xuất — chờ duyệt:** refund case/attempt/result endpoints Admin-only; quyền này chưa được DEC-028 phê duyệt riêng và mặc định deny cho tới sign-off.")

# TEST_PLAN: gate tests on P1 decisions and add acceptance traceability for DEC-029..031.
replace_once("docs/TEST_PLAN.md", "| FR-CT-06, FR-BT-01 | TC-PRODUCT-01, TC-FRESH-01–04 | API/UI/Boundary | P4 | Must |", "| Dữ liệu batch tối thiểu hỗ trợ FR-CT-06 (không gồm batch management) | TC-PRODUCT-01, TC-FRESH-01–04 | API/UI/Boundary | P4 | Must, sau P1 schema approval |")
replace_once("docs/TEST_PLAN.md", "| BR-01–06 | TC-PRICE-01–03 | Unit/Integration | P6/P7 | Must, applicable modules only |", "| BR-01–05 | TC-PRICE-01–03 | Unit/Integration | P6/P7 | Must, áp dụng phần MVP; points/subscription chỉ khi module được bật |")
replace_once("docs/TEST_PLAN.md", "| FR-OR-05 | TC-LOOKUP-01–05 | Security/API/E2E | P7 | Selected S |", "| FR-OR-05 | TC-LOOKUP-01–05 | Security/API/E2E | P7 | Selected S; response-field assertions sau P1 field-level sign-off |")
replace_once("docs/TEST_PLAN.md", "| T06 / TC-CART-04 | Guest cart merges on login | Identity follows approved contract; distinct grind stays separate; no line lost | FR-AU-08 |", "| T06 / TC-CART-04 | Guest cart merges on login | After P1 contract approval: atomic reject/no-clamp on stock or max-20 conflict; cart remains unchanged; distinct grind stays separate | FR-AU-08, DEC-025 |")
replace_once("docs/TEST_PLAN.md", "| T19 / TC-PRODUCT-01 | Product detail has an available batch | Show newest available batch per approved data model | FR-CT-06, FR-BT-01 |", "| T19 / TC-PRODUCT-01 | Product detail has an available batch | After P1 schema approval, show newest available batch for freshness; no batch-admin workflow implied | FR-CT-06 minimal batch scope |")
replace_once("docs/TEST_PLAN.md", "| T27 / TC-LOOKUP-01 | Correct order code and phone | Only corresponding order and permitted fields are returned | FR-OR-05 |", "| T27 / TC-LOOKUP-01 | Correct order code and phone | Only corresponding order is returned; assert each allowed/prohibited response field after P1 field-level permission sign-off | FR-OR-05, DEC-030 |")
replace_once("docs/TEST_PLAN.md", "| T31 / TC-LOOKUP-05 | Repeated code enumeration | Anti-enumeration and rate limit are enforced server-side | Security contract |", "| T31 / TC-LOOKUP-05 | Repeated code enumeration | Anti-enumeration and approved rate limit/cooldown are enforced server-side; run after OPEN-008 mechanics sign-off | Security contract, DEC-027 |")
replace_once("docs/TEST_PLAN.md", "| T50 / TC-CONFIG-03 | Invalid/negative/conflicting configuration | Rejected atomically; no partial config update | FR-AD-12 |", "| T50 / TC-CONFIG-03 | Invalid/negative/conflicting configuration | Rejected atomically; no partial config update | FR-AD-12 |\n| T51 / TC-REFUND-01 | Paid order refund attempt fails then retry succeeds | Attempts/events append-only; failed attempt retained; success restocks all allocations exactly once atomically; duplicate success/reversal has no second stock effect | DEC-029; P1 refund contract |\n| T52 / TC-PII-01 | Guest lookup and Staff order list/detail responses | Guest response contains no PII; Staff full address/phone only in authorized delivery-detail context; all other assertions follow signed field matrix | DEC-030; P1 permissions |\n| T53 / TC-INVENTORY-01 | Batch/unbatched lots, allocation and reversal | `pool_kind`/batch relation constraint enforced; allocation records source lot; every balance change has ledger movement; reversal unique per allocation | DEC-031; P1 schema |")
replace_once("docs/TEST_PLAN.md", "| TC-DB-03 | Transaction failure injection | Order and inventory writes rollback together. |", "| TC-DB-03 | Transaction failure injection | Order and inventory writes rollback together. |\n| TC-DB-04 | Inventory ledger reconciliation | Lot balance equals the sum of recorded movements under the approved model; concurrent adjustments do not produce negative stock. |")

# PRD: update open questions to match approved decisions.
replace_once("docs/PRD.md", "3. **Coupon theo phạm vi sản phẩm:** coupon áp dụng toàn đơn hay theo sản phẩm/danh mục; cách lưu và kiểm tra điều kiện loại trừ subscription.", "3. **Coupon details còn mở:** DEC-024 đã chốt category allowlist và empty-list semantics; còn cách xử lý product nhiều category, eligible-value allocation và canonical Guest identity.")
replace_once("docs/PRD.md", "4. **Guest tra cứu đơn:** thời gian giới hạn/chống dò mã đơn và số lần thử; đây là đề xuất bảo mật cần chốt trong thiết kế endpoint.", "4. **Guest tra cứu đơn:** baseline 5/15m theo IP hash, cooldown 15m và lỗi mismatch trung tính đã duyệt; window semantics/proxy/store failure và field-level response vẫn chờ P1 sign-off.")
replace_once("docs/PRD.md", "5. **Tìm kiếm autocomplete:** số lượng kết quả, độ trễ mục tiêu, cách chuẩn hóa tiếng Việt và phạm vi dữ liệu được tìm.", "5. **Tìm kiếm autocomplete:** min 2/max 8/debounce 250ms/p95 ≤300ms đã duyệt; dấu tiếng Việt, p95 measurement scope và benchmark fixture còn mở.")
replace_once("docs/PRD.md", "6. **Lô rang tối thiểu trong MVP:** màn hình quản trị có cho tạo/sửa lô hay chỉ seed dữ liệu; cách xác định lô “còn hàng” để chọn lô mới nhất.", "6. **Lô rang tối thiểu trong MVP:** chỉ dữ liệu phục vụ product detail/freshness thuộc ngoại lệ đã duyệt; batch-management endpoint/workflow không thuộc MVP; quan hệ batch–variant–inventory và source-of-truth cần P1 approval.")
replace_once("docs/PRD.md", "7. **Flavor Radar trong FR-CT-06:** MVP hiển thị bằng SVG tự viết hay thư viện; nếu chưa triển khai Quiz, điểm sản phẩm lấy trực tiếp từ seed.", "7. **Flavor Radar trong FR-CT-06:** cách render và nguồn dữ liệu cần xác nhận; không được kéo full Quiz/persistence vào MVP.")
replace_once("docs/PRD.md", "10. **Số bước checkout:** đã chốt ba bước theo FR-CO-01; cần chốt chi tiết validation và điều hướng giữa ba bước.\n11. **Nguồn chuẩn hóa:** thời điểm chuyển bản Markdown hiện tại thành `docs/SPEC.md` và nội dung nào cần cập nhật để phản ánh quyết định PostgreSQL, BR-10, tiền/coupon và Freshness.", "10. **Số bước checkout:** đã chốt ba bước theo FR-CO-01; cần chốt chi tiết validation và điều hướng giữa ba bước.\n11. **Refund lifecycle:** payment/refund state, cancellation boundary, quyền refund, external confirmation và transaction acceptance phải được sign-off tại P1 trước implementation.")
